import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Share,
  RefreshControl,
  FlatList,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing, borderRadius } from '../styles/theme';
import Header from '../components/Header';
import PaymentService from '../services/paymentService';
import authService from '../services/authService';

export const DayEndSummaryScreen = ({ navigation }) => {
  const [selectedDate, setSelectedDate] = useState(() => new Date().toISOString().split('T')[0]);
  const [transactions, setTransactions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const currentUser = authService.getCurrentUser();

  const loadTransactions = useCallback(async () => {
    try {
      setLoading(true);
      const data = await PaymentService.getTransactions();
      setTransactions(Array.isArray(data) ? data : []);
    } catch (e) {
      console.warn('Error loading day-end transactions:', e);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    loadTransactions();
  }, [loadTransactions]);

  const onRefresh = () => {
    setRefreshing(true);
    loadTransactions();
  };

  // Filter transactions by selected date
  const dayTransactions = useMemo(() => {
    return transactions.filter((t) => {
      const tDate = (t.date || t.paymentDate || '').split('T')[0];
      return tDate === selectedDate;
    });
  }, [transactions, selectedDate]);

  // Mode breakdown
  const summary = useMemo(() => {
    let cashTotal = 0;
    let cashCount = 0;
    let upiTotal = 0;
    let upiCount = 0;
    let bankTotal = 0;
    let bankCount = 0;
    let chequeTotal = 0;
    let chequeCount = 0;

    const agentMap = {};

    dayTransactions.forEach((t) => {
      const amt = Number(t.amount || t.paidAmount || 0);
      const mode = (t.mode || t.paymentMode || 'UPI').toUpperCase();
      const agent = t.agentName || t.recordedBy || currentUser?.name || 'Collector';

      if (mode.includes('CASH')) {
        cashTotal += amt;
        cashCount += 1;
      } else if (mode.includes('UPI')) {
        upiTotal += amt;
        upiCount += 1;
      } else if (mode.includes('BANK') || mode.includes('NEFT') || mode.includes('IMPS')) {
        bankTotal += amt;
        bankCount += 1;
      } else {
        chequeTotal += amt;
        chequeCount += 1;
      }

      if (!agentMap[agent]) {
        agentMap[agent] = { total: 0, count: 0 };
      }
      agentMap[agent].total += amt;
      agentMap[agent].count += 1;
    });

    const totalCollected = cashTotal + upiTotal + bankTotal + chequeTotal;

    return {
      totalCollected,
      totalCount: dayTransactions.length,
      cashTotal,
      cashCount,
      upiTotal,
      upiCount,
      bankTotal,
      bankCount,
      chequeTotal,
      chequeCount,
      agentMap,
    };
  }, [dayTransactions, currentUser]);

  // Share report via WhatsApp / SMS
  const handleShareSummary = async () => {
    const agentLines = Object.entries(summary.agentMap)
      .map(([name, data]) => `• ${name}: ₹${data.total.toLocaleString('en-IN')} (${data.count} txns)`)
      .join('\n');

    const message =
      `📊 *DAY-END COLLECTION SUMMARY*\n` +
      `📅 Date: ${selectedDate}\n` +
      `---------------------------------\n` +
      `💵 Cash: ₹${summary.cashTotal.toLocaleString('en-IN')} (${summary.cashCount} txns)\n` +
      `📱 UPI: ₹${summary.upiTotal.toLocaleString('en-IN')} (${summary.upiCount} txns)\n` +
      `🏦 Bank: ₹${summary.bankTotal.toLocaleString('en-IN')} (${summary.bankCount} txns)\n` +
      (summary.chequeTotal > 0
        ? `🧾 Cheque: ₹${summary.chequeTotal.toLocaleString('en-IN')} (${summary.chequeCount} txns)\n`
        : '') +
      `---------------------------------\n` +
      `💰 *TOTAL COLLECTED: ₹${summary.totalCollected.toLocaleString('en-IN')}*\n` +
      `📦 Total Transactions: ${summary.totalCount}\n` +
      `---------------------------------\n` +
      `👤 *Agent Collections:*\n` +
      (agentLines || '• Direct Collection') +
      `\n---------------------------------\n` +
      `Generated by Vehicle Finance Manager`;

    try {
      await Share.share({ message });
    } catch (e) {
      console.warn('Share error:', e);
    }
  };

  const setDateOffset = (offsetDays) => {
    const d = new Date();
    d.setDate(d.getDate() + offsetDays);
    setSelectedDate(d.toISOString().split('T')[0]);
  };

  const todayStr = new Date().toISOString().split('T')[0];
  const yesterdayStr = new Date(Date.now() - 86400000).toISOString().split('T')[0];

  return (
    <View style={styles.container}>
      <Header
        title="Day-End Summary"
        subtitle="Daily collections, agent breakdown & cash reconciliation"
        showBack
        onBack={() => navigation.goBack()}
        rightAction={
          <TouchableOpacity
            style={styles.shareBtn}
            onPress={handleShareSummary}
            activeOpacity={0.7}
          >
            <Ionicons name="share-social-outline" size={20} color="#ffffff" />
          </TouchableOpacity>
        }
      />

      <ScrollView
        contentContainerStyle={styles.scrollContent}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} colors={[colors.primary]} />}
      >
        {/* Date Selector Filter */}
        <View style={styles.dateFilterContainer}>
          <Text style={styles.filterLabel}>Collection Date</Text>
          <View style={styles.dateButtonsRow}>
            <TouchableOpacity
              style={[styles.dateBtn, selectedDate === todayStr && styles.dateBtnActive]}
              onPress={() => setDateOffset(0)}
              activeOpacity={0.7}
            >
              <Text style={[styles.dateBtnText, selectedDate === todayStr && styles.dateBtnTextActive]}>
                Today
              </Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={[styles.dateBtn, selectedDate === yesterdayStr && styles.dateBtnActive]}
              onPress={() => setDateOffset(-1)}
              activeOpacity={0.7}
            >
              <Text style={[styles.dateBtnText, selectedDate === yesterdayStr && styles.dateBtnTextActive]}>
                Yesterday
              </Text>
            </TouchableOpacity>

            <View style={styles.activeDateBadge}>
              <Ionicons name="calendar-outline" size={14} color={colors.primary} />
              <Text style={styles.activeDateText}>{selectedDate}</Text>
            </View>
          </View>
        </View>

        {/* Grand Total Hero Card */}
        <View style={styles.heroCard}>
          <View style={styles.heroTop}>
            <Text style={styles.heroLabel}>TOTAL COLLECTED</Text>
            <View style={styles.txnCountBadge}>
              <Text style={styles.txnCountText}>{summary.totalCount} Payments</Text>
            </View>
          </View>
          <Text style={styles.heroAmount}>₹{summary.totalCollected.toLocaleString('en-IN')}</Text>
          <Text style={styles.heroSub}>Reconciled for {selectedDate}</Text>
        </View>

        {/* Mode-wise Breakdown Grid */}
        <Text style={styles.sectionHeading}>Payment Mode Breakdown</Text>
        <View style={styles.modesGrid}>
          {/* Cash */}
          <View style={[styles.modeCard, { borderLeftColor: colors.success }]}>
            <View style={styles.modeIconCircle}>
              <Ionicons name="cash-outline" size={20} color={colors.success} />
            </View>
            <View style={styles.modeInfo}>
              <Text style={styles.modeTitle}>Cash in Hand</Text>
              <Text style={styles.modeCount}>{summary.cashCount} payments</Text>
            </View>
            <Text style={[styles.modeAmount, { color: colors.success }]}>
              ₹{summary.cashTotal.toLocaleString('en-IN')}
            </Text>
          </View>

          {/* UPI */}
          <View style={[styles.modeCard, { borderLeftColor: '#3b82f6' }]}>
            <View style={[styles.modeIconCircle, { backgroundColor: '#eff6ff' }]}>
              <Ionicons name="phone-portrait-outline" size={20} color="#3b82f6" />
            </View>
            <View style={styles.modeInfo}>
              <Text style={styles.modeTitle}>UPI / Online</Text>
              <Text style={styles.modeCount}>{summary.upiCount} payments</Text>
            </View>
            <Text style={[styles.modeAmount, { color: '#3b82f6' }]}>
              ₹{summary.upiTotal.toLocaleString('en-IN')}
            </Text>
          </View>

          {/* Bank Transfer */}
          <View style={[styles.modeCard, { borderLeftColor: '#8b5cf6' }]}>
            <View style={[styles.modeIconCircle, { backgroundColor: '#f5f3ff' }]}>
              <Ionicons name="business-outline" size={20} color="#8b5cf6" />
            </View>
            <View style={styles.modeInfo}>
              <Text style={styles.modeTitle}>Bank Transfer / NEFT</Text>
              <Text style={styles.modeCount}>{summary.bankCount} payments</Text>
            </View>
            <Text style={[styles.modeAmount, { color: '#8b5cf6' }]}>
              ₹{summary.bankTotal.toLocaleString('en-IN')}
            </Text>
          </View>
        </View>

        {/* Agent Tracking Breakdown */}
        <Text style={styles.sectionHeading}>Agent & Collector Performance</Text>
        <View style={styles.agentCard}>
          {Object.keys(summary.agentMap).length === 0 ? (
            <Text style={styles.emptyText}>No agent collections recorded for this date.</Text>
          ) : (
            Object.entries(summary.agentMap).map(([agentName, data], index) => (
              <View
                key={agentName}
                style={[
                  styles.agentRow,
                  index > 0 && { borderTopWidth: 1, borderTopColor: '#f1f5f9' },
                ]}
              >
                <View style={styles.agentAvatar}>
                  <Text style={styles.agentAvatarText}>
                    {agentName.charAt(0).toUpperCase()}
                  </Text>
                </View>
                <View style={styles.agentDetails}>
                  <Text style={styles.agentName}>{agentName}</Text>
                  <Text style={styles.agentTxns}>{data.count} collections logged</Text>
                </View>
                <Text style={styles.agentAmount}>₹{data.total.toLocaleString('en-IN')}</Text>
              </View>
            ))
          )}
        </View>

        {/* Today's Transactions List */}
        <View style={styles.txnsHeaderRow}>
          <Text style={styles.sectionHeading}>Day Ledger ({dayTransactions.length})</Text>
          <TouchableOpacity onPress={handleShareSummary} style={styles.shareTextBtn}>
            <Ionicons name="logo-whatsapp" size={16} color={colors.success} />
            <Text style={styles.shareTextBtnLabel}>Share Report</Text>
          </TouchableOpacity>
        </View>

        {dayTransactions.length === 0 ? (
          <View style={styles.emptyState}>
            <Ionicons name="receipt-outline" size={40} color={colors.textMuted} />
            <Text style={styles.emptyTitle}>No Collections on {selectedDate}</Text>
            <Text style={styles.emptySub}>Recorded EMI payments for this date will appear here.</Text>
          </View>
        ) : (
          dayTransactions.map((item, idx) => (
            <View key={item.id || idx} style={styles.txnItem}>
              <View style={styles.txnLeft}>
                <Text style={styles.txnCustomer}>{item.customerName || 'Customer'}</Text>
                <Text style={styles.txnSub}>
                  File #{item.fileNumber} • EMI #{item.emiNumber} • {item.mode || 'UPI'}
                </Text>
              </View>
              <View style={styles.txnRight}>
                <Text style={styles.txnAmount}>+₹{Number(item.amount || 0).toLocaleString('en-IN')}</Text>
                <Text style={styles.txnStatus}>{item.status || 'COMPLETED'}</Text>
              </View>
            </View>
          ))
        )}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    padding: spacing.md,
    paddingBottom: spacing.xxl,
  },
  shareBtn: {
    padding: spacing.xs,
  },
  dateFilterContainer: {
    backgroundColor: '#ffffff',
    padding: spacing.md,
    borderRadius: borderRadius.md,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  filterLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: spacing.xs,
    textTransform: 'uppercase',
  },
  dateButtonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  dateBtn: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: borderRadius.sm,
    backgroundColor: '#f1f5f9',
  },
  dateBtnActive: {
    backgroundColor: colors.primary,
  },
  dateBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  dateBtnTextActive: {
    color: '#ffffff',
  },
  activeDateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 'auto',
    backgroundColor: '#eff6ff',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: borderRadius.sm,
    gap: 4,
  },
  activeDateText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  heroCard: {
    backgroundColor: colors.primaryDark,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 5,
  },
  heroTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  heroLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#93c5fd',
    letterSpacing: 0.8,
  },
  txnCountBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: borderRadius.round,
  },
  txnCountText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ffffff',
  },
  heroAmount: {
    fontSize: 32,
    fontWeight: '800',
    color: '#ffffff',
    marginVertical: 4,
  },
  heroSub: {
    fontSize: 12,
    color: '#bfdbfe',
  },
  sectionHeading: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: spacing.sm,
  },
  modesGrid: {
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  modeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    padding: spacing.md,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderLeftWidth: 4,
  },
  modeIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#f0fdf4',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  modeInfo: {
    flex: 1,
  },
  modeTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  modeCount: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },
  modeAmount: {
    fontSize: 16,
    fontWeight: '700',
  },
  agentCard: {
    backgroundColor: '#ffffff',
    borderRadius: borderRadius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: spacing.lg,
  },
  agentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  agentAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#eff6ff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  agentAvatarText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.primary,
  },
  agentDetails: {
    flex: 1,
  },
  agentName: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  agentTxns: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },
  agentAmount: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  emptyText: {
    fontSize: 13,
    color: colors.textMuted,
    textAlign: 'center',
    paddingVertical: spacing.md,
  },
  txnsHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  shareTextBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  shareTextBtnLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.success,
  },
  emptyState: {
    alignItems: 'center',
    padding: spacing.xl,
    backgroundColor: '#ffffff',
    borderRadius: borderRadius.md,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.textPrimary,
    marginTop: spacing.sm,
  },
  emptySub: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 4,
  },
  txnItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    padding: spacing.md,
    borderRadius: borderRadius.md,
    marginBottom: spacing.xs,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  txnLeft: {
    flex: 1,
  },
  txnCustomer: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  txnSub: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },
  txnRight: {
    alignItems: 'flex-end',
  },
  txnAmount: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.success,
  },
  txnStatus: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textMuted,
    marginTop: 2,
  },
});

export default DayEndSummaryScreen;
